name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Complie
        run: g++ src/main.cpp src/mainwindow.cpp -o main
      - name: Run
        run: ./main
