name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Compile
        run: g++ HW1_binary_hex_converter/src/main.cpp HW1_binary_hex_converter/src/mainwindow.cpp -o main
      - name: Run
        run: ./main
